version: '3'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres-data:/var/lib/postgresql/data

  archive:
    image: olegabu/evm-archive:latest
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=localhost
      - PGDATABASE=postgres
      - EVM_ARCHIVE_SCHEMA=data
      - EVM_ARCHIVE_ENDPOINT=http://localhost:8545
      - EVM_ARCHIVE_FROM_BLOCK=18266721
      - EVM_ARCHIVE_TO_BLOCK=18266721
      - EVM_ARCHIVE_CONTRACTS=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    network_mode: host
    depends_on: 
      - postgres

volumes:
  postgres-data:
    driver: local